@startuml
title Class Diagram: Registration (UC01)

' Controller

class AuthController {
    - authService : AuthService
    + showRegisterPage() : String
    + processRegistration(dto: RegisterRequestDTO) : RegisterResponseDTO
}

'Service

interface AuthService <<interface>> {
    + registerNewAccount(dto: RegisterRequestDTO) : RegisterResponseDTO
}

class AuthServiceImpl {
    - userRepository : UserRepository
    - emailService : EmailService
    + registerNewAccount(dto: RegisterRequestDTO) : RegisterResponseDTO
    - validateInfo(dto: RegisterRequestDTO) : Boolean
    - encodePassword(rawPassword: String) : void
    - createVerificationToken(user: User) : String
}

interface EmailService <<interface>> {
    + sendVerificationEmail(email: String, token: String) : Boolean
}

class EmailServiceImpl {
    + sendVerificationEmail(email: String, token: String) : Boolean
}

' Repository

interface UserRepository <<interface>> {
    + existsByEmail(email: String) : Boolean
    + save(user: User) : User
}


' DTO

class RegisterRequestDTO {
    - fullName : String
    - phone : String
    - email : String
    - password : String
    - confirmPassword : String
}

class RegisterResponseDTO {
    - userId : Long
    - fullName : String
    - email : String
    - status : UserStatus
    - message : String
}

' Entity

class User {
    - id : Long
    - fullName : String
    - phone : String
    - email : String
    - password : String
    - address : String
    - status : UserStatus
    - verificationToken : String
    - verificationTokenExpiryDate : Instant
    - role : Role
    - twoFactorEnabled : boolean
}

' Relationships

' Class implement Interface
AuthServiceImpl ..|> AuthService
EmailServiceImpl ..|> EmailService

' Dependency Injection
AuthController --> AuthService : - authService
AuthServiceImpl --> UserRepository : - userRepository
AuthServiceImpl --> EmailService : - emailService

' Object Usage
AuthController ..> RegisterRequestDTO : <<uses>>
AuthController ..> RegisterResponseDTO : <<returns>>
AuthServiceImpl ..> RegisterRequestDTO : <<uses>>
AuthServiceImpl ..> RegisterResponseDTO : <<creates>>
AuthServiceImpl ..> User : <<creates>>
UserRepository ..> User : <<manages>>
@enduml