@startuml
title Class Diagram: Registration (UC01)

' Controller

class AuthController {
    - authService : AuthService
    + showRegisterPage() : String
    + processRegistration(dto: RegistrationDTO) : String
}

'Service

interface AuthService <<interface>> {
    + registerNewAccount(dto: RegistrationDTO) : User
}

class AuthServiceImpl {
    - userRepository : UserRepository
    - emailService : EmailService
    + registerNewAccount(dto: RegistrationDTO) : User
    - validateInfo(dto: RegistrationDTO) : Boolean
    - encodePassword(rawPassword: String) : void
    - createVerificationToken(user: User) : String
}

interface EmailService <<interface>> {
    + sendVerificationEmail(email: String, token: String) : Boolean
}

class EmailServiceImpl {
    + sendVerificationEmail(email: String, token: String) : Boolean
}

' Repository

interface UserRepository <<interface>> {
    + existsByEmail(email: String) : Boolean
    + save(user: User) : User
}


' Entity & DTO

class RegistrationDTO {
    - fullName : String
    - phone : String
    - email : String
    - password : String
    - confirmPassword : String
}

class User {
    - id : Long
    - fullName : String
    - phone : String
    - email : String
    - password : String
    - address : String
    - status : String
    - verificationToken : String
    - verificationTokenExpiryDate : Date
}

' Relationships

' Class implement Interface
AuthServiceImpl ..|> AuthService
EmailServiceImpl ..|> EmailService

' Dependency Injection
AuthController --> AuthService : - authService
AuthServiceImpl --> UserRepository : - userRepository
AuthServiceImpl --> EmailService : - emailService

' Object Usage
AuthController ..> RegistrationDTO : <<uses>>
AuthServiceImpl ..> RegistrationDTO : <<uses>>
AuthServiceImpl ..> User : <<creates>>
UserRepository ..> User : <<manages>>
@enduml