@startuml
title Class Diagram : View Products (UC09)

' Controller
class ProductController {
    - productService: ProductService
    + showProductsPage() : String
}

' Service

interface ProductService {
    + getProducts(keyword: String) : List<Product>
}

class ProductServiceImpl {
    - productRepository : ProductRepository
    + getProducts(keyword: String) : List<Product>
}

' Repository

interface ProductRepository {
    + findAll() : List<Product>
    + findByNameContaining(keyword: String) : List<Product>
}

' Entity & DTO

class Product {
    - id: Long
    - name: String
    - price: Double
    - category: String
    - description: String
    - status: String
}

class ProductVariant {
    - id: Long
    - size: String
    - color: String
    - stockQuantity: Long
}

class Review {
    - id: Long
    - rating: int
    - comment: String
    - createdAt: Date
}

class ProductImage {
    - id: Long
    - url: String
}

' Relationships

Product "1" *-- "0..*" ProductImage : has >
Product "1" *-- "0..*" ProductVariant : has >
Product "1" *-- "0..*" Review : receives >

' Class implement Interface
ProductServiceImpl ..|>ProductService

' Dependency Injection
ProductController --> ProductService: - productService
ProductServiceImpl --> ProductRepository: - productRepository

' Object Usage
ProductController ..> Product : <<uses>>
ProductServiceImpl ..> Product : <<uses>>
ProductRepository ..> Product : <<manages>>

@enduml