@startuml
title Class Diagram : Place Order (UC11)

' Controller
class OrderController {
    - orderService: OrderService
    + processOrder(dto: PlaceOrderRequestDTO) : PlaceOrderResponseDTO
}

' Service

interface OrderService <<interface>>{
    + placeOrder(dto: PlaceOrderRequestDTO) : PlaceOrderResponseDTO
}

class OrderServiceImpl {
    + placeOrder(dto: PlaceOrderRequestDTO) : PlaceOrderResponseDTO
    - calculateTotalAmount() : Double
    - productVariantRepository: ProductVariantRepository
    - orderRepository: OrderRepository
    - orderItemRepository: OrderItemRepository
    - cartRepository: CartRepository
    - couponRepository: CouponRepository
}

' Repository
interface ProductVariantRepository <<interface>> {
    + findById(variantId: Long) : ProductVariant
    + save(variant: ProductVariant) : ProductVariant
}

interface OrderRepository <<interface>> {
    + save(order: Order) : Order
}

interface OrderItemRepository <<interface>> {
    + save(orderItem: OrderItem) : OrderItem
}

interface CartRepository <<interface>> {
    + deleteAllById(selectedCartItemIds: List<Long>) : void
}

interface CouponRepository <<interface>> {
    + findByCode(code: String) : Coupon
}

' DTO

class PlaceOrderRequestDTO {
    - cartItemIds : List<Long>
    - shippingAddress : String
    - paymentMethod : PaymentMethod
    - couponCode : String
}

class PlaceOrderResponseDTO {
    - orderId : Long
    - totalAmount : Double
    - status : OrderStatus
    - message : String
}

' Entity

class Order {
    - id : Long
    - orderDate : Date
    - totalAmount : Double
    - status : OrderStatus
    - shippingAddress : String
    - paymentMethod : PaymentMethod
    - type : OrderType
    - cancellationReason : String
    - refundStatus : RefundStatus
}

class OrderItem {
    - id : Long
    - quantity : Long
    - price : Double
    - productName : String
}

class ProductVariant {
    - id : Long
    - size : String
    - color : String
    - stockQuantity : Long
}

class Coupon {
    - id : Long
    - code : String
    - discountValue : Double
    - discountType : DiscountType
    - startDate : Instant
    - expiryDate : Instant
    - minOrderAmount : Double
    - usageLimit : Integer
    - active : boolean
}

class User {
    - id : Long
    - address : String
}

' Relationships

Order "1" *-- "1..*" OrderItem : contains >
Order "N" --> "1" User : belongs to >
Order "N" --> "0..1" Coupon : applies >
OrderItem "N" --> "1" ProductVariant : references >

' Class implement Interface
OrderServiceImpl ..|> OrderService

' Dependency Injection
OrderController --> OrderService: - orderService
OrderServiceImpl --> ProductVariantRepository: - productVariantRepository
OrderServiceImpl --> OrderRepository: - orderRepository
OrderServiceImpl --> OrderItemRepository: - orderItemRepository
OrderServiceImpl --> CartRepository: - cartRepository
OrderServiceImpl --> CouponRepository: - couponRepository

' Object Usage
OrderController ..> PlaceOrderRequestDTO : <<uses>>
OrderController ..> PlaceOrderResponseDTO : <<returns>>
OrderServiceImpl ..> PlaceOrderRequestDTO : <<uses>>
OrderServiceImpl ..> PlaceOrderResponseDTO : <<creates>>

OrderRepository ..> Order : <<manages>>
OrderServiceImpl ..> Order : <<creates>>

ProductVariantRepository ..> ProductVariant : <<manages>>
OrderServiceImpl ..> ProductVariant : <<uses>>

OrderItemRepository ..> OrderItem : <<manages>>
OrderServiceImpl ..> OrderItem : <<creates>>
@enduml