@startuml
title Class Diagram : Place Order (UC11)

' Controller
class OrderController {
    - orderService: OrderService
    + processOrder(orderData: OrderDTO) : String
}

' Service

interface OrderService <<interface>>{
    + placeOrder(orderDto: OrderDTO) : OrderSuccessDTO
}

class OrderServiceImpl {
    + placeOrder(orderDto: OrderDTO) : OrderSuccessDTO
    - calculateTotalAmount() : Double
    - productVariantRepository: ProductVariantRepository
    - orderRepository: OrderRepository
    - orderItemRepository: OrderItemRepository
    - cartRepository: CartRepository
    - couponRepository: CouponRepository
}

' Repository
interface ProductVariantRepository <<interface>> {
    + findById(variantId: Long) : ProductVariant
    + save(variant: ProductVariant) : ProductVariant
}

interface OrderRepository <<interface>> {
    + save(order: Order) : Order
}

interface OrderItemRepository <<interface>> {
    + save(orderItem: OrderItem) : OrderItem
}

interface CartRepository <<interface>> {
    + deleteAllById(selectedCartItemIds: List<Long>) : void
}

interface CouponRepository <<interface>> {
    + findByCode(code: String) : Coupon
}

' Entity & DTO
class OrderDTO {
    - cartItemIds: List<Long>
    - shippingAddress: String
    - paymentMethod: String
    - couponCode: String
}

class OrderSuccessDTO {
    - orderId: Long
    - totalAmount: Double
    - message: String
}

class Order {
    - id : Long
    - orderDate : Date
    - totalAmount : Double
    - status : String
    - shippingAddress : String
    - paymentMethod : String
    - type : String
    - cancellationReason : String
    - refundStatus : String
}

class OrderItem {
    - id : Long
    - quantity : Long
    - price : Double
    - productName : String
}

class ProductVariant {
    - id : Long
    - size : String
    - color : String
    - stockQuantity : Long
}

class Coupon {
    - id : Long
    - code : String
    - discountValue : Double
    - discountType : String
}

class User {
    - id : Long
    - address : String
}

' Relationships

Order "1" *-- "1..*" OrderItem : contains >
Order "N" --> "1" User : belongs to >
Order "N" --> "0..1" Coupon : applies >
OrderItem "N" --> "1" ProductVariant : references >

' Class implement Interface
OrderServiceImpl ..|> OrderService

' Dependency Injection
OrderController --> OrderService: - orderService
OrderServiceImpl --> ProductVariantRepository: - productVariantRepository
OrderServiceImpl --> OrderRepository: - orderRepository
OrderServiceImpl --> OrderItemRepository: - orderItemRepository
OrderServiceImpl --> CartRepository: - cartRepository
OrderServiceImpl --> CouponRepository: - couponRepository

' Object Usage
OrderController ..> OrderDTO : <<uses>>
OrderController ..> OrderSuccessDTO : <<uses>>
OrderServiceImpl ..> OrderDTO : <<uses>>
OrderServiceImpl ..> OrderSuccessDTO : <<creates>>

OrderRepository ..> Order : <<manages>>
OrderServiceImpl ..> Order : <<creates>>

ProductVariantRepository ..> ProductVariant : <<manages>>
OrderServiceImpl ..> ProductVariant : <<uses>>

OrderItemRepository ..> OrderItem : <<manages>>
OrderServiceImpl ..> OrderItem : <<creates>>
@enduml