@startuml
title Class Diagram : Payment (UC12)

' Controller
class PaymentController {
    - paymentService : PaymentService
    + showPaymentPage(orderId: Long) : String
    + processPayment(dto: ProcessPaymentRequestDTO) : PaymentResponseDTO
}

' Service
interface PaymentService <<interface>> {
    + getOrderDetails(orderId: Long) : Order
    + processPayment(dto: ProcessPaymentRequestDTO) : PaymentResponseDTO
}

class PaymentServiceImpl {
    - orderRepository : OrderRepository
    - paymentGateway : PaymentGateway
    + getOrderDetails(orderId: Long) : Order
    + processPayment(dto: ProcessPaymentRequestDTO) : PaymentResponseDTO
}

' External Gateway Service
interface PaymentGateway <<interface>> {
    + requestPayment(amount: Double, orderInfo: String) : PaymentResponseDTO
}

' Repository
interface OrderRepository <<interface>> {
    + findById(orderId: Long) : Order
    + save(order: Order) : Order
}

' DTO

class ProcessPaymentRequestDTO {
    - orderId : Long
    - paymentMethod : PaymentMethod
}

class PaymentResponseDTO {
    - status : String
    - transactionId : String
    - message : String
}

' Entity

class Order {
    - id : Long
    - totalAmount : Double
    - status : OrderStatus
    - paymentMethod : PaymentMethod
    - orderDate : Date
    - cancellationReason : String
    - refundStatus : RefundStatus
}

' Relationships

' Class implement Interface
PaymentServiceImpl ..|> PaymentService

' Dependency Injection
PaymentController --> PaymentService : - paymentService
PaymentServiceImpl --> OrderRepository : - orderRepository
PaymentServiceImpl --> PaymentGateway : - paymentGateway

' Object Usage
PaymentController ..> ProcessPaymentRequestDTO : <<uses>>
PaymentController ..> PaymentResponseDTO : <<returns>>
PaymentServiceImpl ..> ProcessPaymentRequestDTO : <<uses>>
PaymentServiceImpl ..> Order : <<uses>>
OrderRepository ..> Order : <<manages>>

PaymentGateway ..> PaymentResponseDTO : <<creates>>
PaymentServiceImpl ..> PaymentResponseDTO : <<uses>>

@enduml