@startuml
left to right direction
skinparam packageStyle rectangle
actor "Customer" as C

rectangle "Fashion Store System" {

    usecase "Registration" as UC_Regis
    usecase "Account Verification" as UC_AccVerifi
    usecase "Check Existing Account" as UC_CheckExistAcc

    ' Quan hệ Bắt buộc (Include) '
    UC_Regis ..> UC_AccVerifi : <<include>>
    UC_Regis ..> UC_CheckExistAcc : <<include>>

}

' Kết nối Actor '
C -- UC_Regis
note right of UC_AccVerifi : System sends a verification link to User's Email
note right of UC_CheckExistAcc : Verifies that Email, Phone, and UserName \ndo not exist in the database.
@enduml