@startuml
left to right direction
skinparam packageStyle rectangle
actor "Customer" as C
actor "Owner" as O

rectangle "Fashion Store System" {

    usecase "View Products" as UC_ViewPro
    usecase "Search Products" as UC_SearchPro
    usecase "View Product Details" as UC_ViewProDet
    usecase "Filter Products" as UC_FilPro

    UC_SearchPro ..> UC_ViewPro : <<extends>>
    UC_ViewProDet ..> UC_ViewPro : <<extends>>
    UC_FilPro ..> UC_ViewPro : <<extends>>
}

' Kết nối Actor '
C -- UC_ViewPro
O -- UC_ViewPro
@enduml