@startuml
left to right direction
skinparam packageStyle rectangle
actor "Customer" as C

rectangle "Fashion Store System" {

    usecase "Place Order" as UC_PlaceOrd
    usecase "Select Shipping info" as UC_SelShipInfo
    usecase "Apply Discount Coupon" as UC_AppDisCou
    usecase "Select Payment Method" as UC_SelPayMeth

    ' Quan hệ Bắt buộc (Include) '
    UC_PlaceOrd ..> UC_AppDisCou : <<include>>
    UC_PlaceOrd ..> UC_SelShipInfo : <<include>>
    UC_PlaceOrd ..> UC_SelPayMeth : <<include>>

}

' Kết nối Actor '
C -- UC_PlaceOrd
@enduml