@startuml
left to right direction
skinparam packageStyle rectangle

actor "Customer" as C
actor "Payment Gateway" as PG <<System>>

rectangle "Fashion Store System" {
    usecase "Payment" as UC_Payment
    usecase "Select Payment Method" as UC_SelPayMeth
    usecase "Check Payment Timeout" as UC_CheckPayTimeout
    usecase "Change Payment Method" as UC_ChangePayMeth

    C -- UC_Payment

    ''' Quan hệ bắt buộc '''
    UC_Payment ..> UC_SelPayMeth : <<include>>
    UC_Payment ..> UC_CheckPayTimeout : <<include>>

    ''' Quan hệ mở rộng (AF2) '''
    UC_ChangePayMeth ..> UC_Payment : <<extend>>

    ''' Kết nối với cổng thanh toán bên ngoài '''
    UC_Payment -- PG
}
@enduml
