@startuml
left to right direction
skinparam packageStyle rectangle

actor "Customer" as C

rectangle "Fashion Store System" {
    usecase "Submit Return Request" as UC_SubReturnReq
    usecase "Select Products to Return" as UC_SelProToRet
    usecase "Check Return Conditions" as UC_CheckRetCondi
    usecase "Submit Evidence and Reason" as UC_SubEviandRea

    C -- UC_SubReturnReq

    ''' Các bước bắt buộc theo Đặc tả '''
    UC_SubReturnReq ..> UC_SelProToRet : <<include>>
    UC_SubReturnReq ..> UC_CheckRetCondi : <<include>>
    UC_SubReturnReq ..> UC_SubEviandRea : <<include>>
}
@enduml
