@startuml
left to right direction
skinparam packageStyle rectangle

actor "Owner" as O

rectangle "Fashion Store System" {
    usecase "Order Management" as UC_OrdManage
    usecase "View Order List" as UC_VieOrdList
    usecase "View Order Details" as UC_VieOrdDetails
    usecase "Update Order Status" as UC_UpOrdStatus

    O -- UC_OrdManage

    ''' Luồng xem là bắt buộc trong quản lý '''
    UC_OrdManage ..> UC_VieOrdList : <<include>>
    UC_OrdManage ..> UC_VieOrdDetails : <<include>>

    ''' Luồng cập nhật là tùy chọn '''
    UC_UpOrdStatus ..> UC_OrdManage : <<extend>>
}
@enduml
