@startuml
left to right direction
skinparam packageStyle rectangle

actor "Owner" as O

rectangle "Fashion Store System" {
    usecase "Revenue Statistics" as UC_RevSta
    usecase "Select Time Period" as UC_SelTimePeri
    usecase "View Online Revenue" as UC_VieOnRev
    usecase "View Offline Revenue" as UCVieOffRev
    usecase "View Order Details" as UC_VieOrdDet

    O -- UC_RevSta

    ''' Các phần bắt buộc để có báo cáo hoàn chỉnh '''
    UC_RevSta ..> UC_SelTimePeri : <<include>>
    UC_RevSta ..> UC_VieOnRev : <<include>>
    UC_RevSta ..> UCVieOffRev : <<include>>

    ''' Tùy chọn xem chi tiết sản phẩm trong đơn hàng '''
    UC_RevSta ..> UC_VieOrdDet : <<extend>>
}
@enduml
