@startuml
title Activity Diagram (Swimlane) - Registration (UC01)

|Client (UI)|
start
:Mở trang đăng ký;
:Nhập thông tin (fullName, phone, email, password, confirmPassword);
:Nhấn "Đăng ký";
:Gửi request POST /api/auth/register (RegisterRequestDTO);

|System (Service)|
:Validate thông tin (ex: mật khẩu khớp);

if (Thông tin hợp lệ?) then (Không)
    |Client (UI)|
    :Hiển thị lỗi validate;
    stop
else (Có)
    |System (Service)|
    :Kiểm tra trùng email/số điện thoại;

    if (Dữ liệu đã tồn tại?) then (Có)
        |Client (UI)|
        :Hiển thị thông báo (Email / SĐT đã tồn tại);
        stop
    else (Không)
        |System (Service)|
        :Mã hóa mật khẩu;
        :Tạo đối tượng User (status = PENDING);
        :Tạo verification token và gắn vào User;

        |Database (MySQL)|
        :Lưu User;

        |System (Service)|
        if (Lưu DB thành công?) then (Có)
            |Email Service|
            :Thử gửi email xác thực kèm token;
            if (Gửi email thành công?) then (Có)
                |Client (UI)|
                :Hiển thị "Đăng ký thành công. Vui lòng kiểm tra email";
            else (Không - Bị lỗi)
                |Client (UI)|
                :Hiển thị "Đăng ký thành công nhưng không thể gửi email. Nhờ dùng tính năng 'Gửi lại mã'";
            endif
        else (Không)
            |System (Service)|
            :Ném ngoại lệ lỗi lưu trữ;
            |Client (UI)|
            :Hiển thị lỗi hệ thống;
            stop
        endif
    endif
endif

|Client (UI)|
if (Người dùng chọn "Gửi lại mã"?) then (Có)
    :Gửi request POST /api/auth/resend-verification;
    |System (Service)|
    :Tạo token mới cho User;
    |Database (MySQL)|
    :Cập nhật cập token;
    |Email Service|
    :Gửi lại email xác thực;
    |Client (UI)|
    :Hiển thị "Gửi lại email thành công";
else (Không)
endif

stop
@enduml
